spring.datasource.url=jdbc:postgresql://db:5432/greenmind
spring.datasource.username=greenmind_user
spring.datasource.password=greenmind_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
